name: code_notes_frontend dev

run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        env: 
            CI: ""