name: code_notes_frontend test

run-name: ${{ github.event.head_commit.message }}
on:
    workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
            sudo apt update
            sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v3"
        with:
            config_file: .github/workflows/config.ovpn
            client_key: ${{ secrets.OPEN_VPN_PRIVATE_KEY }}

      - uses: appleboy/ssh-action@v1.2.0
        with: 
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          script: |
            cd /root/code_notes
            touch vpn_worked.txt
            